### PR TITLE
Import Markdown Cheatsheet

### PR DESCRIPTION
**Pull request by ST0PPELB4RT**
basically copied everything from the [Pad](https://pad.fsi.uni-tuebingen.de/lightning-talk_Markdown) I used in the lightning talk

### CODE REVIEW

**Comment by ST0PPELB4RT** [comment]
I might not know how I should name the file. Feel free to update it.

**Comment by primeos** [comment]
Probably should've mentioned that, but feel free to use squash & merge (GitHub) or autosquash ([console](https://fle.github.io/git-tip-keep-your-branch-clean-with-fixup-and-autosquash.html)) next time. But it doesn't really matter that much...

**Comment by ST0PPELB4RT** [comment]
@primeos du hasts verkackt, dass sollte als .md-file bleiben und nicht als html gerendert werden...

**Comment by luoe** [comment]
> We shouldn't be switching file formats. Stick with pdf.

This is especially confusing when when viewing files in the folder e.g. on the web interface.

**Comment by primeos** [comment]
> @primeos du hasts verkackt, dass sollte als .md-file bleiben und nicht als html gerendert werden...

@ST0PPELB4RT Nein, das war Absicht! Ich hab das vom Pad extra als HTML exportiert, damit es richtig gerendert wird. Die Markdown Datei würde von GitHub Page ebenfalls gerendert werden, jedoch mit GFM, was nicht dem Markdown rendering vom Pad entspricht. Idealerweise wären alle Markdown Befehle z.B. nochmal in einem Code-Block angegeben. Die Markdown-Datei selber ist noch im `src`-Ordner (die Trennung ist so gedacht).

Die Alternative wäre also das: https://fsi-tue.github.io/workshops/src/lightning-talks/Markdown_Cheatsheet

> We shouldn't be switching file formats. Stick with pdf.

@luoe I agree. We're using PDFs if possible ("Im PDF-Format (nach Möglichkeit)" - README.md), but it doesn't always make sense. In this case the target is HTML (the pad outputs HTML, the PDF export is still in beta and doesn't support all features (-> rendering issues), and this is neither a presentation nor was it designed to fit on a specific paper size (e.g. A4)). Therefore HTML makes most sense IMO. But feel free to modify the source-file if you want to properly convert it to a PDF.

**Comment by luoe** [comment]
> 
> > We shouldn't be switching file formats. Stick with pdf.
> 
> @luoe I agree. We're using PDFs if possible ("Im PDF-Format (nach Möglichkeit)" - README.md), but it doesn't always make sense. In this case the target is HTML (the pad outputs HTML, the PDF export is still in beta and doesn't support all features (-> rendering issues), and this is neither a presentation nor was it designed to fit on a specific paper size (e.g. A4)). Therefore HTML makes most sense IMO. But feel free to modify the source-file if you want to properly convert it to a PDF.
> 
> **Edit**:
> 
> > This is especially confusing when viewing files in the folder e.g. on the web interface.
> 
> In the repository this probably doesn't work well, but that's a problem in general. This is why we use GitHub Pages: https://fsi-tue.github.io/workshops/

This is fine. I also can't get other (than the built-in CodiMD) markdown-to-pdf converter to convert it properly. 

Closing this request for now.

**Comment by primeos** [comment]
> Edit: not closing, but adding the enhancement tag, if we find a proper converter.

Just FYI: This PR is already closed (merged) and won't show up by default. If it's important to you, it would make sense to create a new issue for this (but there are probably more important matters atm).

**Pull request merged**
